//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFile/BackMsg.proto
namespace Platform.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankC2S")]
  public partial class GetRankC2S : global::ProtoBuf.IExtensible
  {
    public GetRankC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankS2C")]
  public partial class GetRankS2C : global::ProtoBuf.IExtensible
  {
    public GetRankS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.RankItem> _ranks = new global::System.Collections.Generic.List<Platform.Model.RankItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ranks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.RankItem> ranks
    {
      get { return _ranks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankItem")]
  public partial class RankItem : global::ProtoBuf.IExtensible
  {
    public RankItem() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetProductListC2S")]
  public partial class GetProductListC2S : global::ProtoBuf.IExtensible
  {
    public GetProductListC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetProductListS2C")]
  public partial class GetProductListS2C : global::ProtoBuf.IExtensible
  {
    public GetProductListS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.Productinfo> _productInfo = new global::System.Collections.Generic.List<Platform.Model.Productinfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"productInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.Productinfo> productInfo
    {
      get { return _productInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Productinfo")]
  public partial class Productinfo : global::ProtoBuf.IExtensible
  {
    public Productinfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _numb;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"numb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numb
    {
      get { return _numb; }
      set { _numb = value; }
    }
    private int _rmb;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rmb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rmb
    {
      get { return _rmb; }
      set { _rmb = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOrderInfoC2S")]
  public partial class GetOrderInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetOrderInfoC2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOrderInfoS2C")]
  public partial class GetOrderInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetOrderInfoS2C() {}
    
    private double _amount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private string _payid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string payid
    {
      get { return _payid; }
      set { _payid = value; }
    }
    private string _goodsName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"goodsName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string goodsName
    {
      get { return _goodsName; }
      set { _goodsName = value; }
    }
    private int _playerid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PaySuccessC2S")]
  public partial class PaySuccessC2S : global::ProtoBuf.IExtensible
  {
    public PaySuccessC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PaySuccessS2C")]
  public partial class PaySuccessS2C : global::ProtoBuf.IExtensible
  {
    public PaySuccessS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}