//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFile/Battle.proto
// Note: requires additional types generated from: ProtoFile/Hall.proto
namespace Platform.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomServerC2S")]
  public partial class EnterRoomServerC2S : global::ProtoBuf.IExtensible
  {
    public EnterRoomServerC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomServerS2C")]
  public partial class EnterRoomServerS2C : global::ProtoBuf.IExtensible
  {
    public EnterRoomServerS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomC2S")]
  public partial class JoinRoomC2S : global::ProtoBuf.IExtensible
  {
    public JoinRoomC2S() {}
    
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomS2C")]
  public partial class JoinRoomS2C : global::ProtoBuf.IExtensible
  {
    public JoinRoomS2C() {}
    
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _innings;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"innings", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int innings
    {
      get { return _innings; }
      set { _innings = value; }
    }
    private int _curInnings;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"curInnings", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curInnings
    {
      get { return _curInnings; }
      set { _curInnings = value; }
    }
    private bool _isStart;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isStart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isStart
    {
      get { return _isStart; }
      set { _isStart = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PlayerInfoVOS2C> _playInfoArr = new global::System.Collections.Generic.List<Platform.Model.PlayerInfoVOS2C>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playInfoArr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PlayerInfoVOS2C> playInfoArr
    {
      get { return _playInfoArr; }
    }
  
    private Platform.Model.PushPlayerActTipS2C _playerTipAct = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerTipAct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Platform.Model.PushPlayerActTipS2C playerTipAct
    {
      get { return _playerTipAct; }
      set { _playerTipAct = value; }
    }
    private int _createId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"createId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int createId
    {
      get { return _createId; }
      set { _createId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _playType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"playType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> playType
    {
      get { return _playType; }
    }
  
    private int _leftCardCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"leftCardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftCardCount
    {
      get { return _leftCardCount; }
      set { _leftCardCount = value; }
    }
    private long _startTime = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private bool _hasDisloveApply = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hasDisloveApply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool hasDisloveApply
    {
      get { return _hasDisloveApply; }
      set { _hasDisloveApply = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _agreeIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"agreeIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> agreeIds
    {
      get { return _agreeIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _refuseIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"refuseIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> refuseIds
    {
      get { return _refuseIds; }
    }
  
    private int _disloveRemainTime = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"disloveRemainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int disloveRemainTime
    {
      get { return _disloveRemainTime; }
      set { _disloveRemainTime = value; }
    }
    private long _disloveRemainUT = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"disloveRemainUT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long disloveRemainUT
    {
      get { return _disloveRemainUT; }
      set { _disloveRemainUT = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tingCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"tingCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tingCards
    {
      get { return _tingCards; }
    }
  
    private int _playerNum = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"playerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerNum
    {
      get { return _playerNum; }
      set { _playerNum = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _dices = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"dices", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dices
    {
      get { return _dices; }
    }
  
    private int _optUserId = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"optUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int optUserId
    {
      get { return _optUserId; }
      set { _optUserId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissolveRoomC2S")]
  public partial class DissolveRoomC2S : global::ProtoBuf.IExtensible
  {
    public DissolveRoomC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissolveRoomS2C")]
  public partial class DissolveRoomS2C : global::ProtoBuf.IExtensible
  {
    public DissolveRoomS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomC2S")]
  public partial class ExitRoomC2S : global::ProtoBuf.IExtensible
  {
    public ExitRoomC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomS2C")]
  public partial class ExitRoomS2C : global::ProtoBuf.IExtensible
  {
    public ExitRoomS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private int _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyDissolveRoomC2S")]
  public partial class ApplyDissolveRoomC2S : global::ProtoBuf.IExtensible
  {
    public ApplyDissolveRoomC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyDissolveRoomS2C")]
  public partial class ApplyDissolveRoomS2C : global::ProtoBuf.IExtensible
  {
    public ApplyDissolveRoomS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelDissolveRoomC2S")]
  public partial class CancelDissolveRoomC2S : global::ProtoBuf.IExtensible
  {
    public CancelDissolveRoomC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelDissolveRoomS2C")]
  public partial class CancelDissolveRoomS2C : global::ProtoBuf.IExtensible
  {
    public CancelDissolveRoomS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissloveRoomConfirmC2S")]
  public partial class DissloveRoomConfirmC2S : global::ProtoBuf.IExtensible
  {
    public DissloveRoomConfirmC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissloveRoomConfirmS2C")]
  public partial class DissloveRoomConfirmS2C : global::ProtoBuf.IExtensible
  {
    public DissloveRoomConfirmS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoVOS2C")]
  public partial class PlayerInfoVOS2C : global::ProtoBuf.IExtensible
  {
    public PlayerInfoVOS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _sit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sit
    {
      get { return _sit; }
      set { _sit = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _isMaster;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isMaster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isMaster
    {
      get { return _isMaster; }
      set { _isMaster = value; }
    }
    private string _headIcon = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private bool _isReady = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isReady
    {
      get { return _isReady; }
      set { _isReady = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private bool _isBanker = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isBanker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBanker
    {
      get { return _isBanker; }
      set { _isBanker = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _handCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> handCards
    {
      get { return _handCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _flowerCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"flowerCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> flowerCards
    {
      get { return _flowerCards; }
    }
  
    private int _getCard = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"getCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int getCard
    {
      get { return _getCard; }
      set { _getCard = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> _pengGangCards = new global::System.Collections.Generic.List<Platform.Model.PengGangCardVO>();
    [global::ProtoBuf.ProtoMember(14, Name=@"pengGangCards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> pengGangCards
    {
      get { return _pengGangCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _putCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"putCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> putCards
    {
      get { return _putCards; }
    }
  
    private bool _isOnline = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> _chiCards = new global::System.Collections.Generic.List<Platform.Model.PengGangCardVO>();
    [global::ProtoBuf.ProtoMember(17, Name=@"chiCards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> chiCards
    {
      get { return _chiCards; }
    }
  
    private bool _isBaoTing = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isBaoTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBaoTing
    {
      get { return _isBaoTing; }
      set { _isBaoTing = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PengGangCardVO")]
  public partial class PengGangCardVO : global::ProtoBuf.IExtensible
  {
    public PengGangCardVO() {}
    
    private readonly global::System.Collections.Generic.List<int> _pengGangCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pengGangCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pengGangCards
    {
      get { return _pengGangCards; }
    }
  
    private int _targetUserId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetUserId
    {
      get { return _targetUserId; }
      set { _targetUserId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushPlayerActTipS2C")]
  public partial class PushPlayerActTipS2C : global::ProtoBuf.IExtensible
  {
    public PushPlayerActTipS2C() {}
    
    private int _optUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"optUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int optUserId
    {
      get { return _optUserId; }
      set { _optUserId = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PlayerActType> _acts = new global::System.Collections.Generic.List<Platform.Model.PlayerActType>();
    [global::ProtoBuf.ProtoMember(2, Name=@"acts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<Platform.Model.PlayerActType> acts
    {
      get { return _acts; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _actCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"actCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> actCards
    {
      get { return _actCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _forbitCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"forbitCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> forbitCards
    {
      get { return _forbitCards; }
    }
  
    private int _tipRemainTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tipRemainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tipRemainTime
    {
      get { return _tipRemainTime; }
      set { _tipRemainTime = value; }
    }
    private long _tipRemainUT = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tipRemainUT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tipRemainUT
    {
      get { return _tipRemainUT; }
      set { _tipRemainUT = value; }
    }
    private int _targetUserId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"targetUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetUserId
    {
      get { return _targetUserId; }
      set { _targetUserId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _chenDiaoCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"chenDiaoCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> chenDiaoCards
    {
      get { return _chenDiaoCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushPlayerActS2C")]
  public partial class PushPlayerActS2C : global::ProtoBuf.IExtensible
  {
    public PushPlayerActS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private Platform.Model.PlayerActType _act;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"act", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Platform.Model.PlayerActType act
    {
      get { return _act; }
      set { _act = value; }
    }
    private int _actCard = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actCard
    {
      get { return _actCard; }
      set { _actCard = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _chiCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"chiCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> chiCards
    {
      get { return _chiCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _flowerCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"flowerCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> flowerCards
    {
      get { return _flowerCards; }
    }
  
    private int _targetUserId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"targetUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetUserId
    {
      get { return _targetUserId; }
      set { _targetUserId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _baoCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"baoCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> baoCards
    {
      get { return _baoCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerMatchResultVOS2C")]
  public partial class PlayerMatchResultVOS2C : global::ProtoBuf.IExtensible
  {
    public PlayerMatchResultVOS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> _pengGangs = new global::System.Collections.Generic.List<Platform.Model.PengGangCardVO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pengGangs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PengGangCardVO> pengGangs
    {
      get { return _pengGangs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _handCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> handCards
    {
      get { return _handCards; }
    }
  
    private int _addScore;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"addScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addScore
    {
      get { return _addScore; }
      set { _addScore = value; }
    }
    private string _huDesc = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"huDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string huDesc
    {
      get { return _huDesc; }
      set { _huDesc = value; }
    }
    private int _anGangCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"anGangCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int anGangCount
    {
      get { return _anGangCount; }
      set { _anGangCount = value; }
    }
    private int _mingGangCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mingGangCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mingGangCount
    {
      get { return _mingGangCount; }
      set { _mingGangCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRoomResultVOS2C")]
  public partial class PlayerRoomResultVOS2C : global::ProtoBuf.IExtensible
  {
    public PlayerRoomResultVOS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _selfHuCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"selfHuCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selfHuCount
    {
      get { return _selfHuCount; }
      set { _selfHuCount = value; }
    }
    private int _otherHuCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"otherHuCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int otherHuCount
    {
      get { return _otherHuCount; }
      set { _otherHuCount = value; }
    }
    private int _sendPaoCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sendPaoCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sendPaoCount
    {
      get { return _sendPaoCount; }
      set { _sendPaoCount = value; }
    }
    private int _anGangCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"anGangCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anGangCount
    {
      get { return _anGangCount; }
      set { _anGangCount = value; }
    }
    private int _mingGangCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mingGangCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mingGangCount
    {
      get { return _mingGangCount; }
      set { _mingGangCount = value; }
    }
    private int _addScore;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"addScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addScore
    {
      get { return _addScore; }
      set { _addScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushMatchResultS2C")]
  public partial class PushMatchResultS2C : global::ProtoBuf.IExtensible
  {
    public PushMatchResultS2C() {}
    
    private readonly global::System.Collections.Generic.List<int> _huUserId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"huUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> huUserId
    {
      get { return _huUserId; }
    }
  
    private int _huedUserId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"huedUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int huedUserId
    {
      get { return _huedUserId; }
      set { _huedUserId = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.PlayerMatchResultVOS2C> _resultInfos = new global::System.Collections.Generic.List<Platform.Model.PlayerMatchResultVOS2C>();
    [global::ProtoBuf.ProtoMember(3, Name=@"resultInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PlayerMatchResultVOS2C> resultInfos
    {
      get { return _resultInfos; }
    }
  
    private int _jiePaoUserId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"jiePaoUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jiePaoUserId
    {
      get { return _jiePaoUserId; }
      set { _jiePaoUserId = value; }
    }
    private int _ziMoUserId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ziMoUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ziMoUserId
    {
      get { return _ziMoUserId; }
      set { _ziMoUserId = value; }
    }
    private int _huedCard = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"huedCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int huedCard
    {
      get { return _huedCard; }
      set { _huedCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushRoomResultS2C")]
  public partial class PushRoomResultS2C : global::ProtoBuf.IExtensible
  {
    public PushRoomResultS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.PlayerRoomResultVOS2C> _resultInfos = new global::System.Collections.Generic.List<Platform.Model.PlayerRoomResultVOS2C>();
    [global::ProtoBuf.ProtoMember(2, Name=@"resultInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.PlayerRoomResultVOS2C> resultInfos
    {
      get { return _resultInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushJoinS2C")]
  public partial class PushJoinS2C : global::ProtoBuf.IExtensible
  {
    public PushJoinS2C() {}
    
    private Platform.Model.PlayerInfoVOS2C _playerInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Platform.Model.PlayerInfoVOS2C playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushSendChatS2C")]
  public partial class PushSendChatS2C : global::ProtoBuf.IExtensible
  {
    public PushSendChatS2C() {}
    
    private int _senderUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"senderUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int senderUserId
    {
      get { return _senderUserId; }
      set { _senderUserId = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushVoiceS2C")]
  public partial class PushVoiceS2C : global::ProtoBuf.IExtensible
  {
    public PushVoiceS2C() {}
    
    private int _senderUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"senderUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int senderUserId
    {
      get { return _senderUserId; }
      set { _senderUserId = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendVoiceC2S")]
  public partial class SendVoiceC2S : global::ProtoBuf.IExtensible
  {
    public SendVoiceC2S() {}
    
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _flag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendChatC2S")]
  public partial class SendChatC2S : global::ProtoBuf.IExtensible
  {
    public SendChatC2S() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushReadyS2C")]
  public partial class PushReadyS2C : global::ProtoBuf.IExtensible
  {
    public PushReadyS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyC2S")]
  public partial class ReadyC2S : global::ProtoBuf.IExtensible
  {
    public ReadyC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"touHeTipS2C")]
  public partial class touHeTipS2C : global::ProtoBuf.IExtensible
  {
    public touHeTipS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"touHeC2S")]
  public partial class touHeC2S : global::ProtoBuf.IExtensible
  {
    public touHeC2S() {}
    
    private int _touHeCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"touHeCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int touHeCode
    {
      get { return _touHeCode; }
      set { _touHeCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"touHeS2C")]
  public partial class touHeS2C : global::ProtoBuf.IExtensible
  {
    public touHeS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _touHeCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"touHeCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int touHeCode
    {
      get { return _touHeCode; }
      set { _touHeCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoTingTipS2C")]
  public partial class baoTingTipS2C : global::ProtoBuf.IExtensible
  {
    public baoTingTipS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoJiaTipS2C")]
  public partial class baoJiaTipS2C : global::ProtoBuf.IExtensible
  {
    public baoJiaTipS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoDiaoTipS2C")]
  public partial class baoDiaoTipS2C : global::ProtoBuf.IExtensible
  {
    public baoDiaoTipS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"chenDiaoTipS2C")]
  public partial class chenDiaoTipS2C : global::ProtoBuf.IExtensible
  {
    public chenDiaoTipS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoTingC2S")]
  public partial class baoTingC2S : global::ProtoBuf.IExtensible
  {
    public baoTingC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoTingS2C")]
  public partial class baoTingS2C : global::ProtoBuf.IExtensible
  {
    public baoTingS2C() {}
    
    private readonly global::System.Collections.Generic.List<int> _mahjongCode = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mahjongCode
    {
      get { return _mahjongCode; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoJiaC2S")]
  public partial class baoJiaC2S : global::ProtoBuf.IExtensible
  {
    public baoJiaC2S() {}
    
    private int _baoJiaCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"baoJiaCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int baoJiaCode
    {
      get { return _baoJiaCode; }
      set { _baoJiaCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoJiaS2C")]
  public partial class baoJiaS2C : global::ProtoBuf.IExtensible
  {
    public baoJiaS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoDiaoC2S")]
  public partial class baoDiaoC2S : global::ProtoBuf.IExtensible
  {
    public baoDiaoC2S() {}
    
    private int _baoDiaoCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"baoDiaoCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int baoDiaoCode
    {
      get { return _baoDiaoCode; }
      set { _baoDiaoCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"baoDiaoS2C")]
  public partial class baoDiaoS2C : global::ProtoBuf.IExtensible
  {
    public baoDiaoS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"chenDiaoC2S")]
  public partial class chenDiaoC2S : global::ProtoBuf.IExtensible
  {
    public chenDiaoC2S() {}
    
    private int _chenDiaoCards;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chenDiaoCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chenDiaoCards
    {
      get { return _chenDiaoCards; }
      set { _chenDiaoCards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"chenDiaoS2C")]
  public partial class chenDiaoS2C : global::ProtoBuf.IExtensible
  {
    public chenDiaoS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushOnlineSettingS2C")]
  public partial class PushOnlineSettingS2C : global::ProtoBuf.IExtensible
  {
    public PushOnlineSettingS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isOnline;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnlineSettingC2S")]
  public partial class OnlineSettingC2S : global::ProtoBuf.IExtensible
  {
    public OnlineSettingC2S() {}
    
    private bool _isOnline;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushBettingS2C")]
  public partial class PushBettingS2C : global::ProtoBuf.IExtensible
  {
    public PushBettingS2C() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BettingC2S")]
  public partial class BettingC2S : global::ProtoBuf.IExtensible
  {
    public BettingC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStart_S2C")]
  public partial class GameStart_S2C : global::ProtoBuf.IExtensible
  {
    public GameStart_S2C() {}
    
    private int _bankerUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bankerUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bankerUserId
    {
      get { return _bankerUserId; }
      set { _bankerUserId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _dices = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dices", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dices
    {
      get { return _dices; }
    }
  
    private int _currentTimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currentTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentTimes
    {
      get { return _currentTimes; }
      set { _currentTimes = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _handCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> handCards
    {
      get { return _handCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _flowerCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"flowerCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> flowerCards
    {
      get { return _flowerCards; }
    }
  
    private int _touchMahjongCode;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"touchMahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int touchMahjongCode
    {
      get { return _touchMahjongCode; }
      set { _touchMahjongCode = value; }
    }
    private int _leftCardCount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"leftCardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftCardCount
    {
      get { return _leftCardCount; }
      set { _leftCardCount = value; }
    }
    private Platform.Model.PushPlayerActTipS2C _pushPlayerActTipS2C;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pushPlayerActTipS2C", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Platform.Model.PushPlayerActTipS2C pushPlayerActTipS2C
    {
      get { return _pushPlayerActTipS2C; }
      set { _pushPlayerActTipS2C = value; }
    }
    private long _startTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayAMahjongC2S")]
  public partial class PlayAMahjongC2S : global::ProtoBuf.IExtensible
  {
    public PlayAMahjongC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuoC2S")]
  public partial class GuoC2S : global::ProtoBuf.IExtensible
  {
    public GuoC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PengC2S")]
  public partial class PengC2S : global::ProtoBuf.IExtensible
  {
    public PengC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiC2S")]
  public partial class ChiC2S : global::ProtoBuf.IExtensible
  {
    public ChiC2S() {}
    
    private readonly global::System.Collections.Generic.List<int> _mahjongCodes = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mahjongCodes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mahjongCodes
    {
      get { return _mahjongCodes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _forbitCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"forbitCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> forbitCards
    {
      get { return _forbitCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonAnGangC2S")]
  public partial class CommonAnGangC2S : global::ProtoBuf.IExtensible
  {
    public CommonAnGangC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackAnGangC2S")]
  public partial class BackAnGangC2S : global::ProtoBuf.IExtensible
  {
    public BackAnGangC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZhiGangC2S")]
  public partial class ZhiGangC2S : global::ProtoBuf.IExtensible
  {
    public ZhiGangC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonPengGangC2S")]
  public partial class CommonPengGangC2S : global::ProtoBuf.IExtensible
  {
    public CommonPengGangC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackPengGangC2S")]
  public partial class BackPengGangC2S : global::ProtoBuf.IExtensible
  {
    public BackPengGangC2S() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZiMoHuC2S")]
  public partial class ZiMoHuC2S : global::ProtoBuf.IExtensible
  {
    public ZiMoHuC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangZhiGangHuC2S")]
  public partial class QiangZhiGangHuC2S : global::ProtoBuf.IExtensible
  {
    public QiangZhiGangHuC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangAnGangHuC2S")]
  public partial class QiangAnGangHuC2S : global::ProtoBuf.IExtensible
  {
    public QiangAnGangHuC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangPengGangHuC2S")]
  public partial class QiangPengGangHuC2S : global::ProtoBuf.IExtensible
  {
    public QiangPengGangHuC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiHuC2S")]
  public partial class ChiHuC2S : global::ProtoBuf.IExtensible
  {
    public ChiHuC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActErrorS2C")]
  public partial class ActErrorS2C : global::ProtoBuf.IExtensible
  {
    public ActErrorS2C() {}
    
    private Platform.Model.PlayerActType _act;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"act", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Platform.Model.PlayerActType act
    {
      get { return _act; }
      set { _act = value; }
    }
    private int _errorCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayAMahjongS2C")]
  public partial class PlayAMahjongS2C : global::ProtoBuf.IExtensible
  {
    public PlayAMahjongS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tingCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tingCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tingCards
    {
      get { return _tingCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuoS2C")]
  public partial class GuoS2C : global::ProtoBuf.IExtensible
  {
    public GuoS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PengS2C")]
  public partial class PengS2C : global::ProtoBuf.IExtensible
  {
    public PengS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiS2C")]
  public partial class ChiS2C : global::ProtoBuf.IExtensible
  {
    public ChiS2C() {}
    
    private readonly global::System.Collections.Generic.List<int> _mahjongCodes = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mahjongCodes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mahjongCodes
    {
      get { return _mahjongCodes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _forbitCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"forbitCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> forbitCards
    {
      get { return _forbitCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonAnGangS2C")]
  public partial class CommonAnGangS2C : global::ProtoBuf.IExtensible
  {
    public CommonAnGangS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackAnGangS2C")]
  public partial class BackAnGangS2C : global::ProtoBuf.IExtensible
  {
    public BackAnGangS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZhiGangS2C")]
  public partial class ZhiGangS2C : global::ProtoBuf.IExtensible
  {
    public ZhiGangS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonPengGangS2C")]
  public partial class CommonPengGangS2C : global::ProtoBuf.IExtensible
  {
    public CommonPengGangS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackPengGangS2C")]
  public partial class BackPengGangS2C : global::ProtoBuf.IExtensible
  {
    public BackPengGangS2C() {}
    
    private int _mahjongCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mahjongCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mahjongCode
    {
      get { return _mahjongCode; }
      set { _mahjongCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZiMoHuS2C")]
  public partial class ZiMoHuS2C : global::ProtoBuf.IExtensible
  {
    public ZiMoHuS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangZhiGangHuS2C")]
  public partial class QiangZhiGangHuS2C : global::ProtoBuf.IExtensible
  {
    public QiangZhiGangHuS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangAnGangHuS2C")]
  public partial class QiangAnGangHuS2C : global::ProtoBuf.IExtensible
  {
    public QiangAnGangHuS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangPengGangHuS2C")]
  public partial class QiangPengGangHuS2C : global::ProtoBuf.IExtensible
  {
    public QiangPengGangHuS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiHuS2C")]
  public partial class ChiHuS2C : global::ProtoBuf.IExtensible
  {
    public ChiHuS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleBeatC2S")]
  public partial class BattleBeatC2S : global::ProtoBuf.IExtensible
  {
    public BattleBeatC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleBeatS2C")]
  public partial class BattleBeatS2C : global::ProtoBuf.IExtensible
  {
    public BattleBeatS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerActType")]
    public enum PlayerActType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_CARD", Value=1)]
      GET_CARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUT_CARD", Value=2)]
      PUT_CARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PENG", Value=3)]
      PENG = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHI", Value=4)]
      CHI = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZHI_GANG", Value=5)]
      ZHI_GANG = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON_PENG_GANG", Value=6)]
      COMMON_PENG_GANG = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BACK_PENG_GANG", Value=7)]
      BACK_PENG_GANG = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON_AN_GANG", Value=8)]
      COMMON_AN_GANG = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BACK_AN_GANG", Value=9)]
      BACK_AN_GANG = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASS", Value=10)]
      PASS = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF_HU", Value=11)]
      SELF_HU = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QIANG_ZHI_GANG_HU", Value=12)]
      QIANG_ZHI_GANG_HU = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QIANG_AN_GANG_HU", Value=13)]
      QIANG_AN_GANG_HU = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QIANG_PENG_GANG_HU", Value=14)]
      QIANG_PENG_GANG_HU = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHI_HU", Value=15)]
      CHI_HU = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOU_HE", Value=16)]
      TOU_HE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAO_TING", Value=17)]
      BAO_TING = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAO_JIA", Value=18)]
      BAO_JIA = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAO_DIAO", Value=19)]
      BAO_DIAO = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHENG_DIAO", Value=20)]
      CHENG_DIAO = 20
    }
  
}