//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFile/CoreHall.proto
// Note: requires additional types generated from: ProtoFile/Hall.proto
namespace Platform.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreJoinInRoomS2C")]
  public partial class CoreJoinInRoomS2C : global::ProtoBuf.IExtensible
  {
    public CoreJoinInRoomS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private int _roomRounds = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private int _roomRule = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRule
    {
      get { return _roomRule; }
      set { _roomRule = value; }
    }
    private string _roomServerIp = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomServerIp
    {
      get { return _roomServerIp; }
      set { _roomServerIp = value; }
    }
    private int _roomServerPort = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomServerPort
    {
      get { return _roomServerPort; }
      set { _roomServerPort = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private string _playType = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playType
    {
      get { return _playType; }
      set { _playType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreGetUserInfoS2C")]
  public partial class CoreGetUserInfoS2C : global::ProtoBuf.IExtensible
  {
    public CoreGetUserInfoS2C() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private string _showId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"showId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string showId
    {
      get { return _showId; }
      set { _showId = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _boundAgency = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"boundAgency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int boundAgency
    {
      get { return _boundAgency; }
      set { _boundAgency = value; }
    }
    private int _agencyID = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"agencyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int agencyID
    {
      get { return _agencyID; }
      set { _agencyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreGradeDataS2C")]
  public partial class CoreGradeDataS2C : global::ProtoBuf.IExtensible
  {
    public CoreGradeDataS2C() {}
    
    private int _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> _usersInfo = new global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C>();
    [global::ProtoBuf.ProtoMember(5, Name=@"usersInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> usersInfo
    {
      get { return _usersInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreRoundData")]
  public partial class CoreRoundData : global::ProtoBuf.IExtensible
  {
    public CoreRoundData() {}
    
    private int _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> _usersInfo = new global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C>();
    [global::ProtoBuf.ProtoMember(5, Name=@"usersInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> usersInfo
    {
      get { return _usersInfo; }
    }
  
    private int _reportId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"reportId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reportId
    {
      get { return _reportId; }
      set { _reportId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreRemoveAgercyC2S")]
  public partial class CoreRemoveAgercyC2S : global::ProtoBuf.IExtensible
  {
    public CoreRemoveAgercyC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreRemoveAgercyS2C")]
  public partial class CoreRemoveAgercyS2C : global::ProtoBuf.IExtensible
  {
    public CoreRemoveAgercyS2C() {}
    
    private bool _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreOrederInfoC2S")]
  public partial class CoreOrederInfoC2S : global::ProtoBuf.IExtensible
  {
    public CoreOrederInfoC2S() {}
    
    private int _price;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreOrederInfoS2C")]
  public partial class CoreOrederInfoS2C : global::ProtoBuf.IExtensible
  {
    public CoreOrederInfoS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreGMKickUserC2S")]
  public partial class CoreGMKickUserC2S : global::ProtoBuf.IExtensible
  {
    public CoreGMKickUserC2S() {}
    
    private readonly global::System.Collections.Generic.List<int> _userIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> userIds
    {
      get { return _userIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreGMKickUserS2C")]
  public partial class CoreGMKickUserS2C : global::ProtoBuf.IExtensible
  {
    public CoreGMKickUserS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoreGMAddItemC2S")]
  public partial class CoreGMAddItemC2S : global::ProtoBuf.IExtensible
  {
    public CoreGMAddItemC2S() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _itemType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _addNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"addNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addNum
    {
      get { return _addNum; }
      set { _addNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}