//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFile/Hall.proto
namespace Platform.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DialogS2C")]
  public partial class DialogS2C : global::ProtoBuf.IExtensible
  {
    public DialogS2C() {}
    
    private int _dialogCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dialogCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dialogCode
    {
      get { return _dialogCode; }
      set { _dialogCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckCreateRoomC2S")]
  public partial class CheckCreateRoomC2S : global::ProtoBuf.IExtensible
  {
    public CheckCreateRoomC2S() {}
    
    private int _roomRounds;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private int _roomRule;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomRule
    {
      get { return _roomRule; }
      set { _roomRule = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _playType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> playType
    {
      get { return _playType; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckCreateRoomS2C")]
  public partial class CheckCreateRoomS2C : global::ProtoBuf.IExtensible
  {
    public CheckCreateRoomS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private string _roomServerIp = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomServerIp
    {
      get { return _roomServerIp; }
      set { _roomServerIp = value; }
    }
    private int _roomServerPort = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomServerPort
    {
      get { return _roomServerPort; }
      set { _roomServerPort = value; }
    }
    private string _roomCode = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _seat;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinInRoomC2S")]
  public partial class JoinInRoomC2S : global::ProtoBuf.IExtensible
  {
    public JoinInRoomC2S() {}
    
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinInRoomS2C")]
  public partial class JoinInRoomS2C : global::ProtoBuf.IExtensible
  {
    public JoinInRoomS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private int _roomRounds = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private int _roomRule = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRule
    {
      get { return _roomRule; }
      set { _roomRule = value; }
    }
    private string _roomServerIp = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomServerIp
    {
      get { return _roomServerIp; }
      set { _roomServerIp = value; }
    }
    private int _roomServerPort = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomServerPort
    {
      get { return _roomServerPort; }
      set { _roomServerPort = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCardInfoC2S")]
  public partial class GetCardInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetCardInfoC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCardInfoS2C")]
  public partial class GetCardInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetCardInfoS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddCardInfoC2S")]
  public partial class AddCardInfoC2S : global::ProtoBuf.IExtensible
  {
    public AddCardInfoC2S() {}
    
    private int _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddCardInfoS2C")]
  public partial class AddCardInfoS2C : global::ProtoBuf.IExtensible
  {
    public AddCardInfoS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCheckInInfoC2S")]
  public partial class GetCheckInInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetCheckInInfoC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCheckInInfoS2C")]
  public partial class GetCheckInInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetCheckInInfoS2C() {}
    
    private int _days;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"days", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int days
    {
      get { return _days; }
      set { _days = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckInC2S")]
  public partial class CheckInC2S : global::ProtoBuf.IExtensible
  {
    public CheckInC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckInS2C")]
  public partial class CheckInS2C : global::ProtoBuf.IExtensible
  {
    public CheckInS2C() {}
    
    private int _clientCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientCode
    {
      get { return _clientCode; }
      set { _clientCode = value; }
    }
    private int _days = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"days", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int days
    {
      get { return _days; }
      set { _days = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCheckInRewardC2S")]
  public partial class GetCheckInRewardC2S : global::ProtoBuf.IExtensible
  {
    public GetCheckInRewardC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCheckInRewardS2C")]
  public partial class GetCheckInRewardS2C : global::ProtoBuf.IExtensible
  {
    public GetCheckInRewardS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserItem")]
  public partial class UserItem : global::ProtoBuf.IExtensible
  {
    public UserItem() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoC2S")]
  public partial class GetUserInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetUserInfoC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoS2C")]
  public partial class GetUserInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetUserInfoS2C() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private string _showId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"showId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string showId
    {
      get { return _showId; }
      set { _showId = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _boundAgency = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"boundAgency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int boundAgency
    {
      get { return _boundAgency; }
      set { _boundAgency = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGradeInfoC2S")]
  public partial class GetGradeInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetGradeInfoC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGradeInfoS2C")]
  public partial class GetGradeInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetGradeInfoS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.GradeDataS2C> _gradeDataS2C = new global::System.Collections.Generic.List<Platform.Model.GradeDataS2C>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gradeDataS2C", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.GradeDataS2C> gradeDataS2C
    {
      get { return _gradeDataS2C; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GradeDataS2C")]
  public partial class GradeDataS2C : global::ProtoBuf.IExtensible
  {
    public GradeDataS2C() {}
    
    private int _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> _usersInfo = new global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C>();
    [global::ProtoBuf.ProtoMember(4, Name=@"usersInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> usersInfo
    {
      get { return _usersInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoundInfoC2S")]
  public partial class GetRoundInfoC2S : global::ProtoBuf.IExtensible
  {
    public GetRoundInfoC2S() {}
    
    private int _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoundInfoS2C")]
  public partial class GetRoundInfoS2C : global::ProtoBuf.IExtensible
  {
    public GetRoundInfoS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.RoundData> _roundData = new global::System.Collections.Generic.List<Platform.Model.RoundData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roundData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.RoundData> roundData
    {
      get { return _roundData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoundData")]
  public partial class RoundData : global::ProtoBuf.IExtensible
  {
    public RoundData() {}
    
    private int _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> _usersInfo = new global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C>();
    [global::ProtoBuf.ProtoMember(4, Name=@"usersInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UsersInfoS2C> usersInfo
    {
      get { return _usersInfo; }
    }
  
    private int _reportId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"reportId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reportId
    {
      get { return _reportId; }
      set { _reportId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UsersInfoS2C")]
  public partial class UsersInfoS2C : global::ProtoBuf.IExtensible
  {
    public UsersInfoS2C() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private string _headImgUrl = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headImgUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImgUrl
    {
      get { return _headImgUrl; }
      set { _headImgUrl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckApplyStatusC2S")]
  public partial class CheckApplyStatusC2S : global::ProtoBuf.IExtensible
  {
    public CheckApplyStatusC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckApplyStatusS2C")]
  public partial class CheckApplyStatusS2C : global::ProtoBuf.IExtensible
  {
    public CheckApplyStatusS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private long _currentTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"currentTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long currentTime
    {
      get { return _currentTime; }
      set { _currentTime = value; }
    }
    private long _startTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyCompetitionC2S")]
  public partial class ApplyCompetitionC2S : global::ProtoBuf.IExtensible
  {
    public ApplyCompetitionC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyCompetitionS2C")]
  public partial class ApplyCompetitionS2C : global::ProtoBuf.IExtensible
  {
    public ApplyCompetitionS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinCompetitionC2S")]
  public partial class JoinCompetitionC2S : global::ProtoBuf.IExtensible
  {
    public JoinCompetitionC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinCompetitionS2C")]
  public partial class JoinCompetitionS2C : global::ProtoBuf.IExtensible
  {
    public JoinCompetitionS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckInvitationCodeC2S")]
  public partial class CheckInvitationCodeC2S : global::ProtoBuf.IExtensible
  {
    public CheckInvitationCodeC2S() {}
    
    private int _invitationId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"invitationId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int invitationId
    {
      get { return _invitationId; }
      set { _invitationId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckInvitationCodeS2C")]
  public partial class CheckInvitationCodeS2C : global::ProtoBuf.IExtensible
  {
    public CheckInvitationCodeS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushAnnouncementS2C")]
  public partial class PushAnnouncementS2C : global::ProtoBuf.IExtensible
  {
    public PushAnnouncementS2C() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _cirCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cirCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cirCount
    {
      get { return _cirCount; }
      set { _cirCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyMatchingC2S")]
  public partial class ApplyMatchingC2S : global::ProtoBuf.IExtensible
  {
    public ApplyMatchingC2S() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _roomRounds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyMatchingS2C")]
  public partial class ApplyMatchingS2C : global::ProtoBuf.IExtensible
  {
    public ApplyMatchingS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchingSucceedS2C")]
  public partial class MatchingSucceedS2C : global::ProtoBuf.IExtensible
  {
    public MatchingSucceedS2C() {}
    
    private string _roomCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _roomRounds = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private int _roomRule = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomRule
    {
      get { return _roomRule; }
      set { _roomRule = value; }
    }
    private string _roomServerIp = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomServerIp
    {
      get { return _roomServerIp; }
      set { _roomServerIp = value; }
    }
    private int _roomServerPort = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomServerPort
    {
      get { return _roomServerPort; }
      set { _roomServerPort = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelMatchingC2S")]
  public partial class CancelMatchingC2S : global::ProtoBuf.IExtensible
  {
    public CancelMatchingC2S() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _roomRounds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomRounds
    {
      get { return _roomRounds; }
      set { _roomRounds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelMatchingS2C")]
  public partial class CancelMatchingS2C : global::ProtoBuf.IExtensible
  {
    public CancelMatchingS2C() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankingListC2S")]
  public partial class GetRankingListC2S : global::ProtoBuf.IExtensible
  {
    public GetRankingListC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankingListS2C")]
  public partial class GetRankingListS2C : global::ProtoBuf.IExtensible
  {
    public GetRankingListS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoticeConfigS2C")]
  public partial class NoticeConfigS2C : global::ProtoBuf.IExtensible
  {
    public NoticeConfigS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.NoticeConfigDataS2C> _noticeConfigData = new global::System.Collections.Generic.List<Platform.Model.NoticeConfigDataS2C>();
    [global::ProtoBuf.ProtoMember(1, Name=@"noticeConfigData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.NoticeConfigDataS2C> noticeConfigData
    {
      get { return _noticeConfigData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoticeConfigDataS2C")]
  public partial class NoticeConfigDataS2C : global::ProtoBuf.IExtensible
  {
    public NoticeConfigDataS2C() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoByIdC2S")]
  public partial class GetUserInfoByIdC2S : global::ProtoBuf.IExtensible
  {
    public GetUserInfoByIdC2S() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoByIdS2C")]
  public partial class GetUserInfoByIdS2C : global::ProtoBuf.IExtensible
  {
    public GetUserInfoByIdS2C() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private string _showId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"showId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string showId
    {
      get { return _showId; }
      set { _showId = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _imageUrl;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"imageUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imageUrl
    {
      get { return _imageUrl; }
      set { _imageUrl = value; }
    }
    private int _userId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayVideoC2S")]
  public partial class PlayVideoC2S : global::ProtoBuf.IExtensible
  {
    public PlayVideoC2S() {}
    
    private int _round;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round
    {
      get { return _round; }
      set { _round = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayVideoS2C")]
  public partial class PlayVideoS2C : global::ProtoBuf.IExtensible
  {
    public PlayVideoS2C() {}
    
    private string _report;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"report", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string report
    {
      get { return _report; }
      set { _report = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReConnectC2S")]
  public partial class ReConnectC2S : global::ProtoBuf.IExtensible
  {
    public ReConnectC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReConnectS2C")]
  public partial class ReConnectS2C : global::ProtoBuf.IExtensible
  {
    public ReConnectS2C() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomCode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private string _roomIp = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomIp
    {
      get { return _roomIp; }
      set { _roomIp = value; }
    }
    private int _roomPort = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomPort
    {
      get { return _roomPort; }
      set { _roomPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushUserItem")]
  public partial class PushUserItem : global::ProtoBuf.IExtensible
  {
    public PushUserItem() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.UserItem> _userItems = new global::System.Collections.Generic.List<Platform.Model.UserItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.UserItem> userItems
    {
      get { return _userItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallBeatC2S")]
  public partial class HallBeatC2S : global::ProtoBuf.IExtensible
  {
    public HallBeatC2S() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallBeatS2C")]
  public partial class HallBeatS2C : global::ProtoBuf.IExtensible
  {
    public HallBeatS2C() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetHallRoomListS2C")]
  public partial class GetHallRoomListS2C : global::ProtoBuf.IExtensible
  {
    public GetHallRoomListS2C() {}
    
    private readonly global::System.Collections.Generic.List<Platform.Model.HallRoomInfo> _hallRoomInfo = new global::System.Collections.Generic.List<Platform.Model.HallRoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hallRoomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Platform.Model.HallRoomInfo> hallRoomInfo
    {
      get { return _hallRoomInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HallRoomInfo")]
  public partial class HallRoomInfo : global::ProtoBuf.IExtensible
  {
    public HallRoomInfo() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _numOfGames;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"numOfGames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string numOfGames
    {
      get { return _numOfGames; }
      set { _numOfGames = value; }
    }
    private int _pepole;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pepole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pepole
    {
      get { return _pepole; }
      set { _pepole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}